// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/images/KrankyBearGenealogy.png
var resourceKrankyBearGenealogyPngData []byte
var resourceKrankyBearGenealogyPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearGenealogy.png",
	StaticContent: resourceKrankyBearGenealogyPngData,
}

//go:embed assets/images/KrankyBearGenealogy64.png
var resourceKrankyBearGenealogy64PngData []byte
var resourceKrankyBearGenealogy64Png = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearGenealogy64.png",
	StaticContent: resourceKrankyBearGenealogy64PngData,
}

//go:embed assets/images/KrankyBearHardHat.png
var resourceKrankyBearHardHatPngData []byte
var resourceKrankyBearHardHatPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearHardHat.png",
	StaticContent: resourceKrankyBearHardHatPngData,
}
