package ui

import (
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"os"
	"path/filepath"
	"strings"
	"time"

	"genealogy/store"
	"github.com/jung-kurt/gofpdf"
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/widget"
	"golang.org/x/image/font"
	"golang.org/x/image/font/basicfont"
	"golang.org/x/image/math/fixed"
)

// ExportChartOptions holds options for chart export
type ExportChartOptions struct {
	Title       string
	Format      string // "PDF" or "PNG"
	Width       float64
	Height      float64
	Content     fyne.CanvasObject // The chart content to export
}

// showChartExportDialogWithStore shows export dialog with store access for descendant charts
func showChartExportDialogWithStore(w fyne.Window, title string, content fyne.CanvasObject, people []*store.Person, s *store.Store) {
	showChartExportDialogInternal(w, title, content, people, s)
}

// showChartExportDialog shows a dialog to export a chart
func showChartExportDialog(w fyne.Window, title string, content fyne.CanvasObject, people []*store.Person) {
	showChartExportDialogInternal(w, title, content, people, nil)
}

// showChartExportDialogInternal is the internal implementation
func showChartExportDialogInternal(w fyne.Window, title string, content fyne.CanvasObject, people []*store.Person, s *store.Store) {
	formatSelect := widget.NewSelect([]string{"PDF", "PNG"}, func(string) {})
	formatSelect.SetSelected("PDF")
	
	description := widget.NewLabel(fmt.Sprintf("Export %s", title))
	description.Wrapping = fyne.TextWrapWord
	
	contentBox := container.NewVBox(
		description,
		widget.NewSeparator(),
		widget.NewLabel("Export Format:"),
		formatSelect,
		widget.NewLabel("\nThe file will be saved with the appropriate extension (.pdf or .png)"),
	)
	
	dialog.ShowCustomConfirm("Export Chart", "Export", "Cancel", contentBox, func(export bool) {
		if !export {
			return
		}
		
		format := formatSelect.Selected
		if format == "" {
			dialog.ShowInformation("Format Required", "Please select an export format.", w)
			return
		}
		
		// Determine default extension
		defaultExt := ".pdf"
		if format == "PNG" {
			defaultExt = ".png"
		}
		
		// Generate default filename with timestamp
		timestamp := time.Now().Format("2006-01-02_150405")
		defaultFilename := fmt.Sprintf("%s_%s%s", sanitizeFilename(title), timestamp, defaultExt)
		
		// Show file save dialog with default filename
		saveDialog := dialog.NewFileSave(func(writer fyne.URIWriteCloser, err error) {
			if err != nil {
				dialog.ShowError(err, w)
				return
			}
			if writer == nil {
				return
			}
			
			path := writer.URI().Path()
			originalPath := path
			
			// Close the writer first (it creates an empty file)
			writer.Close()
			
			// Ensure correct extension
			correctPath := path
			if format == "PDF" && filepath.Ext(path) != ".pdf" {
				correctPath = path + ".pdf"
			} else if format == "PNG" && filepath.Ext(path) != ".png" {
				correctPath = path + ".png"
			}
			
			// Remove the empty file if path changed
			if correctPath != originalPath {
				os.Remove(originalPath)
			}
			
			var exportErr error
			if format == "PDF" {
				exportErr = exportChartToPDF(correctPath, title, content, people, s)
			} else {
				exportErr = exportChartToPNG(correctPath, title, content, people, s)
			}
			
			if exportErr != nil {
				dialog.ShowError(fmt.Errorf("Export failed: %v", exportErr), w)
				return
			}
			
			dialog.ShowInformation("Export Complete", fmt.Sprintf("Chart exported successfully to:\n%s", correctPath), w)
		}, w)
		
		// Set default filename
		saveDialog.SetFileName(defaultFilename)
		saveDialog.Show()
	}, w)
}

// exportChartToPDF exports a chart to PDF format
func exportChartToPDF(path string, title string, content fyne.CanvasObject, people []*store.Person, s *store.Store) error {
	// Use landscape for charts
	pdf := gofpdf.New("L", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 15)
	pdf.AddPage()
	
	// Header with title
	pdf.SetFont("Arial", "B", 20)
	pdf.SetTextColor(0, 51, 102)
	pdf.Cell(0, 12, title)
	pdf.Ln(12)
	
	// Subtitle with export date
	pdf.SetFont("Arial", "", 10)
	pdf.SetTextColor(100, 100, 100)
	pdf.Cell(0, 6, fmt.Sprintf("Generated by KrankyBear Genealogy on %s", time.Now().Format("Monday, January 2, 2006 at 3:04 PM")))
	pdf.Ln(10)
	pdf.SetTextColor(0, 0, 0)
	
	// Draw horizontal line
	pdf.SetDrawColor(200, 200, 200)
	pdf.SetLineWidth(0.5)
	pdf.Line(10, pdf.GetY(), 287, pdf.GetY())
	pdf.Ln(8)
	
	// Chart information section
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 8, "Chart Overview:")
	pdf.Ln(10)
	
	pdf.SetFont("Arial", "", 11)
	info := extractChartInfo(content, people)
	pdf.MultiCell(0, 6, info, "", "", false)
	pdf.Ln(8)
	
	// Determine chart type from title and render appropriate structure
	if strings.Contains(title, "Pedigree") || strings.Contains(title, "Fan") {
		// Fan charts show same ancestor data, rendered in pedigree columnar layout for PDF
		renderPedigreeChartPDF(pdf, people, title)
	} else if strings.Contains(title, "Descendant") {
		renderDescendantChartPDF(pdf, people, s)
	} else {
		// Fallback: simple list
		if len(people) > 0 {
			pdf.SetFont("Arial", "B", 12)
			pdf.Cell(0, 8, fmt.Sprintf("People in Chart (%d individuals):", len(people)))
			pdf.Ln(8)
			pdf.SetFont("Arial", "", 10)
			addPeopleList(pdf, people)
		}
	}
	
	// Visual representation note
	pdf.SetFillColor(240, 248, 255)
	pdf.Rect(10, pdf.GetY(), 277, 30, "F")
	pdf.SetFont("Arial", "B", 12)
	pdf.SetTextColor(0, 51, 102)
	pdf.Cell(0, 10, "")
	pdf.Ln(6)
	pdf.Cell(0, 6, "For Full Visual Experience:")
	pdf.Ln(7)
	pdf.SetFont("Arial", "", 10)
	pdf.SetTextColor(0, 0, 0)
	pdf.Cell(0, 6, "Open this chart in KrankyBear Genealogy to see interactive boxes, colors, zoom controls, and navigation features.")
	pdf.Ln(8)
	
	// Footer
	pdf.SetY(-20)
	pdf.SetFont("Arial", "I", 8)
	pdf.SetTextColor(128, 128, 128)
	pdf.CellFormat(0, 10, fmt.Sprintf("Page %d", pdf.PageNo()), "", 0, "C", false, 0, "")
	
	return pdf.OutputFileAndClose(path)
}

// extractChartInfo extracts information from chart content for PDF export
func extractChartInfo(content fyne.CanvasObject, people []*store.Person) string {
	info := fmt.Sprintf("This chart contains %d individuals with their genealogical relationships.\n\n", len(people))
	
	info += "Chart Features Available in Application:\n"
	info += "  - Interactive Navigation: Click any person to view their record\n"
	info += "  - Color Coding: View by gender, living status, or data completeness\n"
	info += "  - Zoom Controls: Scale from 50% to 200%\n"
	info += "  - Collapsible Branches: Focus on specific lineages\n"
	info += "  - Context Menus: Right-click for quick actions\n"
	info += "  - Dynamic Sync: Charts update when navigating in Family View\n"
	info += "  - Visual Indicators: Bookmarks, media, sources, todos, research logs\n\n"
	info += "For the complete interactive experience with all genealogical data and navigation features,\n"
	info += "open this chart in the KrankyBear Genealogy application."
	return info
}

// addPeopleList adds a formatted list of people to the PDF with boxes
func addPeopleList(pdf *gofpdf.Fpdf, people []*store.Person) {
	// Remove duplicates
	seen := make(map[int64]bool)
	uniquePeople := make([]*store.Person, 0)
	for _, p := range people {
		if p != nil && !seen[p.ID] {
			seen[p.ID] = true
			uniquePeople = append(uniquePeople, p)
		}
	}
	
	// Two-column layout
	leftX := 10.0
	rightX := 150.0
	colWidth := 130.0
	boxHeight := 16.0
	
	for i, person := range uniquePeople {
		if i > 0 && i%30 == 0 { // New page after 30 people
			pdf.AddPage()
			pdf.SetY(20.0)
		}
		
		// Alternate between columns
		x := leftX
		if i%2 == 1 {
			x = rightX
		}
		
		// Move to next row every 2 people
		if i > 0 && i%2 == 0 {
			pdf.Ln(boxHeight + 2)
		}
		
		y := pdf.GetY()
		
		// Draw colored box based on gender
		if person.Gender == "M" {
			pdf.SetFillColor(173, 216, 230) // Light blue
			pdf.SetDrawColor(70, 130, 180)  // Steel blue
		} else if person.Gender == "F" {
			pdf.SetFillColor(255, 192, 203) // Pink
			pdf.SetDrawColor(219, 112, 147) // Pale violet red
		} else {
			pdf.SetFillColor(240, 240, 240) // Light gray
			pdf.SetDrawColor(150, 150, 150) // Gray
		}
		
		pdf.SetLineWidth(0.5)
		pdf.Rect(x, y, colWidth, boxHeight, "FD")
		
		// Add person info inside box
		pdf.SetXY(x+3, y+3)
		pdf.SetFont("Arial", "B", 9)
		pdf.SetTextColor(0, 0, 0)
		
		name := formatPersonName(*person)
		if len(name) > 25 {
			name = name[:22] + "..."
		}
		pdf.Cell(colWidth-6, 5, name)
		
		// Add dates on second line
		dates := formatPersonDates(*person)
		if dates != "" {
			pdf.SetXY(x+3, y+9)
			pdf.SetFont("Arial", "", 7)
			pdf.SetTextColor(60, 60, 60)
			if len(dates) > 32 {
				dates = dates[:29] + "..."
			}
			pdf.Cell(colWidth-6, 4, dates)
		}
		
		pdf.SetTextColor(0, 0, 0)
	}
}

// formatPersonDates formats birth and death dates for display
func formatPersonDates(person store.Person) string {
	var parts []string
	
	if person.BirthDate != "" {
		parts = append(parts, "b. "+person.BirthDate)
	}
	if person.DeathDate != "" {
		parts = append(parts, "d. "+person.DeathDate)
	}
	
	if len(parts) > 0 {
		return strings.Join(parts, ", ")
	}
	return ""
}

// renderPedigreeChartPDF renders an ancestor/pedigree chart in PDF matching the app layout
func renderPedigreeChartPDF(pdf *gofpdf.Fpdf, people []*store.Person, chartTitle string) {
	if len(people) == 0 {
		return
	}
	
	pdf.AddPage()
	pdf.SetY(15)
	
	// Draw title
	pdf.SetFont("Arial", "B", 12)
	pdf.SetTextColor(0, 51, 102)
	if strings.Contains(chartTitle, "Fan") {
		pdf.Cell(0, 8, "Ancestor Chart (Pedigree Format)")
		pdf.Ln(6)
		pdf.SetFont("Arial", "I", 9)
		pdf.SetTextColor(80, 80, 80)
		pdf.Cell(0, 6, "Fan chart ancestors shown in columnar pedigree layout for PDF export")
	} else {
		pdf.Cell(0, 8, "Pedigree Chart")
	}
	pdf.Ln(10)
	pdf.SetTextColor(0, 0, 0)
	
	// Organize people by generation (person[0] is root, then parents, grandparents, etc.)
	root := people[0]
	
	// Layout constants - compact to fit all 4 generations
	boxWidth := 50.0
	boxHeight := 18.0
	colWidth := 58.0  // Reduced spacing between columns
	vertSpacing := 22.0
	startX := 12.0
	startY := 100.0  // Moved down to center the chart vertically
	
	// Draw generation labels
	pdf.SetFont("Arial", "B", 9)
	pdf.SetTextColor(100, 100, 100)
	for gen := 0; gen < 4 && float64(gen)*colWidth+startX < 280; gen++ {
		x := startX + float64(gen)*colWidth
		pdf.SetXY(x, 25)
		if gen == 0 {
			pdf.Cell(colWidth, 5, "1st")
		} else if gen == 1 {
			pdf.Cell(colWidth, 5, "2nd")
		} else if gen == 2 {
			pdf.Cell(colWidth, 5, "3rd")
		} else {
			pdf.Cell(colWidth, 5, "4th")
		}
	}
	pdf.SetTextColor(0, 0, 0)
	
	// Generation 1: Root person (use wider box to avoid name truncation)
	y := startY
	rootBoxWidth := 80.0 // Wider for root person
	drawPDFPersonBox(pdf, startX, y, rootBoxWidth, boxHeight, root)
	
	// Generation 2: Parents (indices 1-2 in Ahnentafel)
	if len(people) > 2 {
		x2 := startX + colWidth
		
		// Father (top) - index 1
		if people[1] != nil {
			yFather := y - vertSpacing
			pdf.SetFont("Arial", "", 7)
			pdf.SetXY(x2-15, yFather-3)
			pdf.Cell(15, 3, "Father:")
			drawPDFPersonBox(pdf, x2, yFather, boxWidth, boxHeight, people[1])
			// No line from root to parents - relationship is obvious from labels
			drawPDFArrow(pdf, x2+boxWidth, yFather+boxHeight/2, x2+colWidth-2, yFather+boxHeight/2)
		}
		
		// Mother (bottom) - index 2
		if people[2] != nil {
			yMother := y + vertSpacing
			pdf.SetFont("Arial", "", 7)
			pdf.SetXY(x2-15, yMother-3)
			pdf.Cell(15, 3, "Mother:")
			drawPDFPersonBox(pdf, x2, yMother, boxWidth, boxHeight, people[2])
			// No line from root to parents - relationship is obvious from labels
			drawPDFArrow(pdf, x2+boxWidth, yMother+boxHeight/2, x2+colWidth-2, yMother+boxHeight/2)
		}
	}
	
	// Generation 3: Grandparents (indices 3-6 in Ahnentafel)
	// Ahnentafel: 3=paternal grandfather, 4=paternal grandmother, 5=maternal grandfather, 6=maternal grandmother
	if len(people) > 6 {
		x3 := startX + 2*colWidth
		yFather := y - vertSpacing // Father's Y position
		yMother := y + vertSpacing // Mother's Y position
		
		// Paternal grandparents (father's parents) - indices 3 and 4
		// Paternal grandfather (index 3) - top of father's line
		if people[3] != nil {
			yPG := yFather - vertSpacing/2
			drawPDFPersonBox(pdf, x3, yPG, boxWidth, boxHeight, people[3])
			drawPDFArrow(pdf, x3+boxWidth, yPG+boxHeight/2, x3+colWidth-2, yPG+boxHeight/2)
		}
		
		// Paternal grandmother (index 4) - bottom of father's line
		if people[4] != nil {
			yPGM := yFather + vertSpacing/2
			drawPDFPersonBox(pdf, x3, yPGM, boxWidth, boxHeight, people[4])
			drawPDFArrow(pdf, x3+boxWidth, yPGM+boxHeight/2, x3+colWidth-2, yPGM+boxHeight/2)
		}
		
		// Maternal grandparents (mother's parents) - indices 5 and 6
		// Maternal grandfather (index 5) - top of mother's line
		if people[5] != nil {
			yMG := yMother - vertSpacing/2
			drawPDFPersonBox(pdf, x3, yMG, boxWidth, boxHeight, people[5])
			drawPDFArrow(pdf, x3+boxWidth, yMG+boxHeight/2, x3+colWidth-2, yMG+boxHeight/2)
		}
		
		// Maternal grandmother (index 6) - bottom of mother's line
		if people[6] != nil {
			yMGM := yMother + vertSpacing/2
			drawPDFPersonBox(pdf, x3, yMGM, boxWidth, boxHeight, people[6])
			drawPDFArrow(pdf, x3+boxWidth, yMGM+boxHeight/2, x3+colWidth-2, yMGM+boxHeight/2)
		}
	}
	
	// Generation 4: Great-grandparents (indices 7-14 in Ahnentafel)
	// 7-8: parents of person 3, 9-10: parents of person 4, 11-12: parents of person 5, 13-14: parents of person 6
	if len(people) > 7 {
		x4 := startX + 3*colWidth
		yFather := y - vertSpacing  // Father's Y position (gen 2)
		yMother := y + vertSpacing  // Mother's Y position (gen 2)
		smallSpacing := vertSpacing / 4
		
		// Calculate grandparent Y positions (gen 3)
		yPG := yFather - vertSpacing/2   // Paternal grandfather (person 3)
		yPGM := yFather + vertSpacing/2  // Paternal grandmother (person 4)
		yMG := yMother - vertSpacing/2   // Maternal grandfather (person 5)
		yMGM := yMother + vertSpacing/2  // Maternal grandmother (person 6)
		
		// Parents of paternal grandfather (person 3) - indices 7, 8
		// These should align with person 3's Y position (yPG)
		if len(people) > 7 && people[7] != nil {
			yGGF1 := yPG - smallSpacing
			if yGGF1 > 15 && yGGF1+boxHeight < 190 {
				drawPDFPersonBox(pdf, x4, yGGF1, boxWidth, boxHeight, people[7])
			}
		}
		if len(people) > 8 && people[8] != nil {
			yGGM1 := yPG + smallSpacing
			if yGGM1 > 15 && yGGM1+boxHeight < 190 {
				drawPDFPersonBox(pdf, x4, yGGM1, boxWidth, boxHeight, people[8])
			}
		}
		
		// Parents of paternal grandmother (person 4) - indices 9, 10
		// These should align with person 4's Y position (yPGM)
		if len(people) > 9 && people[9] != nil {
			yGGF2 := yPGM - smallSpacing
			if yGGF2 > 15 && yGGF2+boxHeight < 190 {
				drawPDFPersonBox(pdf, x4, yGGF2, boxWidth, boxHeight, people[9])
			}
		}
		if len(people) > 10 && people[10] != nil {
			yGGM2 := yPGM + smallSpacing
			if yGGM2 > 15 && yGGM2+boxHeight < 190 {
				drawPDFPersonBox(pdf, x4, yGGM2, boxWidth, boxHeight, people[10])
			}
		}
		
		// Parents of maternal grandfather (person 5) - indices 11, 12
		// These should align with person 5's Y position (yMG)
		if len(people) > 11 && people[11] != nil {
			yGGF3 := yMG - smallSpacing
			if yGGF3 > 15 && yGGF3+boxHeight < 190 {
				drawPDFPersonBox(pdf, x4, yGGF3, boxWidth, boxHeight, people[11])
			}
		}
		if len(people) > 12 && people[12] != nil {
			yGGM3 := yMG + smallSpacing
			if yGGM3 > 15 && yGGM3+boxHeight < 190 {
				drawPDFPersonBox(pdf, x4, yGGM3, boxWidth, boxHeight, people[12])
			}
		}
		
		// Parents of maternal grandmother (person 6) - indices 13, 14
		// These should align with person 6's Y position (yMGM)
		if len(people) > 13 && people[13] != nil {
			yGGF4 := yMGM - smallSpacing
			if yGGF4 > 15 && yGGF4+boxHeight < 190 {
				drawPDFPersonBox(pdf, x4, yGGF4, boxWidth, boxHeight, people[13])
			}
		}
		if len(people) > 14 && people[14] != nil {
			yGGM4 := yMGM + smallSpacing
			if yGGM4 > 15 && yGGM4+boxHeight < 190 {
				drawPDFPersonBox(pdf, x4, yGGM4, boxWidth, boxHeight, people[14])
			}
		}
	}
	
	// Add footer note
	pdf.SetY(190)
	pdf.SetFont("Arial", "I", 8)
	pdf.SetTextColor(100, 100, 100)
	pdf.MultiCell(0, 4, "For Full Visual Experience: Open this chart in KrankyBear Genealogy to see\ninteractive boxes, colors, zoom controls, and navigation features.", "", "C", false)
}

// drawPDFArrow draws a simple arrow line in PDF
func drawPDFArrow(pdf *gofpdf.Fpdf, x1, y1, x2, y2 float64) {
	pdf.SetDrawColor(180, 180, 180)
	pdf.SetLineWidth(0.3)
	pdf.Line(x1, y1, x2, y2)
}

// descendantNode represents a person in the descendant tree with their children
type descendantNode struct {
	person    *store.Person
	children  []*descendantNode
	x, y      float64 // Calculated position
	boxWidth  float64 // Box width (wider for root)
	boxHeight float64 // Box height
}

// renderDescendantChartPDF renders a descendant chart in PDF
func renderDescendantChartPDF(pdf *gofpdf.Fpdf, people []*store.Person, s *store.Store) {
	if len(people) == 0 {
		return
	}
	
	pdf.AddPage()
	pdf.SetY(20)
	
	root := people[0]
	
	// Draw chart title
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 10, "Descendant Chart Structure")
	pdf.Ln(12)
	
	boxWidth := 50.0
	boxHeight := 16.0
	vertSpacing := 25.0
	horizSpacing := 5.0
	
	startX := 15.0 // Start from left to fit wider trees
	startY := 50.0
	
	// Build tree structure from flat list using store
	tree := buildDescendantTreeWithStore(root, s, 4) // 4 generations max
	
	// Set box sizes (root gets wider box)
	rootBoxWidth := 80.0 // Wider for root to avoid truncation
	setBoxSizesPDF(tree, rootBoxWidth, boxWidth, boxHeight, true)
	
	// Calculate positions for all nodes
	calculateDescendantPositions(tree, startX, startY, vertSpacing, horizSpacing)
	
	// Draw the tree
	drawDescendantTreePDF(pdf, tree)
	
	// Add note
	pdf.SetY(240)
	pdf.SetFont("Arial", "I", 9)
	pdf.SetTextColor(100, 100, 100)
	pdf.MultiCell(0, 5, "Note: For the complete interactive chart with all descendants,\nexpanding branches, and navigation features, open in KrankyBear Genealogy application.", "", "L", false)
}

// buildDescendantTreeWithStore builds a proper tree structure using store queries
func buildDescendantTreeWithStore(root *store.Person, s *store.Store, maxGen int) *descendantNode {
	if root == nil || s == nil {
		return nil
	}
	
	return buildDescendantNodeRecursive(root, s, 1, maxGen)
}

// setBoxSizesPDF recursively sets box sizes for PDF rendering
func setBoxSizesPDF(node *descendantNode, rootWidth, childWidth, height float64, isRoot bool) {
	if node == nil {
		return
	}
	
	if isRoot {
		node.boxWidth = rootWidth
	} else {
		node.boxWidth = childWidth
	}
	node.boxHeight = height
	
	for _, child := range node.children {
		setBoxSizesPDF(child, rootWidth, childWidth, height, false)
	}
}

// buildDescendantNodeRecursive recursively builds descendant tree
func buildDescendantNodeRecursive(person *store.Person, s *store.Store, currentGen, maxGen int) *descendantNode {
	if person == nil || currentGen > maxGen {
		return nil
	}
	
	node := &descendantNode{
		person:   person,
		children: []*descendantNode{},
	}
	
	// Get children from store
	children, err := s.GetRelatedPeople(person.ID, "child")
	if err == nil && len(children) > 0 {
		for i := range children {
			childNode := buildDescendantNodeRecursive(&children[i], s, currentGen+1, maxGen)
			if childNode != nil {
				node.children = append(node.children, childNode)
			}
		}
	}
	
	return node
}

// calculateDescendantPositions calculates x,y positions for all nodes in the tree
func calculateDescendantPositions(node *descendantNode, x, y, vertSpacing, horizSpacing float64) float64 {
	if node == nil {
		return x
	}
	
	node.x = x
	node.y = y
	
	if len(node.children) == 0 {
		return x + node.boxWidth + horizSpacing
	}
	
	// Position children below
	childY := y + node.boxHeight + vertSpacing
	childX := x
	
	for _, child := range node.children {
		childX = calculateDescendantPositions(child, childX, childY, vertSpacing, horizSpacing)
	}
	
	// Center parent above children
	if len(node.children) > 0 {
		firstChildX := node.children[0].x
		lastChildX := node.children[len(node.children)-1].x
		node.x = (firstChildX + lastChildX) / 2
	}
	
	return childX
}

// drawDescendantTreePDF draws the descendant tree in PDF
func drawDescendantTreePDF(pdf *gofpdf.Fpdf, node *descendantNode) {
	if node == nil {
		return
	}
	
	// Draw this node using its own box size
	drawPDFPersonBox(pdf, node.x, node.y, node.boxWidth, node.boxHeight, node.person)
	
	// Draw lines to children and recurse
	for _, child := range node.children {
		// Draw line from parent to child
		pdf.SetDrawColor(150, 150, 150)
		pdf.SetLineWidth(0.3)
		parentCenterX := node.x + node.boxWidth/2
		parentBottomY := node.y + node.boxHeight
		childCenterX := child.x + child.boxWidth/2
		childTopY := child.y
		
		// Vertical line from parent
		midY := (parentBottomY + childTopY) / 2
		pdf.Line(parentCenterX, parentBottomY, parentCenterX, midY)
		// Horizontal line to child
		pdf.Line(parentCenterX, midY, childCenterX, midY)
		// Vertical line to child
		pdf.Line(childCenterX, midY, childCenterX, childTopY)
		
		drawDescendantTreePDF(pdf, child)
	}
}

// drawPDFPersonBox draws a person box in PDF with proper formatting
func drawPDFPersonBox(pdf *gofpdf.Fpdf, x, y, width, height float64, person *store.Person) {
	// Set colors based on gender
	if person.Gender == "M" {
		pdf.SetFillColor(173, 216, 230) // Light blue
		pdf.SetDrawColor(70, 130, 180)  // Steel blue
	} else if person.Gender == "F" {
		pdf.SetFillColor(255, 192, 203) // Pink
		pdf.SetDrawColor(219, 112, 147) // Pale violet red
	} else {
		pdf.SetFillColor(240, 240, 240) // Light gray
		pdf.SetDrawColor(150, 150, 150) // Gray
	}
	
	pdf.SetLineWidth(0.4)
	pdf.Rect(x, y, width, height, "FD")
	
	// Add person name
	pdf.SetXY(x+1.5, y+2.5)
	pdf.SetFont("Arial", "B", 7)
	pdf.SetTextColor(0, 0, 0)
	
	name := formatPersonName(*person)
	// Adjust truncation based on box width
	maxChars := int(width / 2.5)  // Rough approximation
	if len(name) > maxChars {
		name = name[:maxChars-3] + "..."
	}
	pdf.Cell(width-3, 4, name)
	
	// Add dates
	dates := formatPersonDates(*person)
	if dates != "" {
		pdf.SetXY(x+1.5, y+8)
		pdf.SetFont("Arial", "", 6)
		pdf.SetTextColor(60, 60, 60)
		maxDateChars := int(width / 2.2)
		if len(dates) > maxDateChars {
			dates = dates[:maxDateChars-3] + "..."
		}
		pdf.Cell(width-3, 3, dates)
	}
	
	// Add location if space permits
	if person.BirthPlace != "" && height > 16 {
		pdf.SetXY(x+1.5, y+12.5)
		pdf.SetFont("Arial", "", 5)
		pdf.SetTextColor(100, 100, 100)
		place := person.BirthPlace
		maxPlaceChars := int(width / 1.8)
		if len(place) > maxPlaceChars {
			place = place[:maxPlaceChars-3] + "..."
		}
		pdf.Cell(width-3, 2.5, place)
	}
	
	pdf.SetTextColor(0, 0, 0)
}


// exportChartToPNG exports a chart to PNG format
func exportChartToPNG(path string, title string, content fyne.CanvasObject, people []*store.Person, s *store.Store) error {
	// Calculate image size based on content
	size := content.Size()
	width := int(size.Width)
	height := int(size.Height)
	
	// Ensure minimum size for proper chart layout
	if width < 1400 {
		width = 1400
	}
	if height < 950 {
		height = 950
	}
	
	// Create an image with light gray background
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	bgColor := color.RGBA{245, 245, 250, 255}
	draw.Draw(img, img.Bounds(), &image.Uniform{bgColor}, image.Point{}, draw.Src)
	
	// Draw title bar
	drawTitleBar(img, width, title)
	
	// Render chart based on type
	if strings.Contains(title, "Pedigree") || strings.Contains(title, "Fan") {
		renderPedigreeChartPNG(img, width, height, people)
	} else if strings.Contains(title, "Descendant") {
		renderDescendantChartPNG(img, width, height, people, s)
	} else {
		// Fallback to grid
		drawPersonBoxes(img, width, height, people)
	}
	
	// Draw chart info footer
	drawChartFooter(img, width, height, len(people))
	
	// Save to file
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()
	
	return png.Encode(file, img)
}

// drawTitleBar draws the title bar at the top of the PNG
func drawTitleBar(img *image.RGBA, width int, title string) {
	// Draw title background
	titleBg := color.RGBA{0, 51, 102, 255}
	for y := 0; y < 60; y++ {
		for x := 0; x < width; x++ {
			img.Set(x, y, titleBg)
		}
	}
	
	// Draw bottom border
	borderColor := color.RGBA{0, 102, 204, 255}
	for x := 0; x < width; x++ {
		for y := 58; y < 60; y++ {
			img.Set(x, y, borderColor)
		}
	}
	
	// Draw title text in white
	if len(title) > 80 {
		title = title[:77] + "..."
	}
	drawText(img, 30, 35, title, color.RGBA{255, 255, 255, 255})
}

// drawPersonBoxes draws boxes for each person in a grid
func drawPersonBoxes(img *image.RGBA, width, height int, people []*store.Person) {
	// Remove duplicates
	seen := make(map[int64]bool)
	uniquePeople := make([]*store.Person, 0)
	for _, p := range people {
		if p != nil && !seen[p.ID] {
			seen[p.ID] = true
			uniquePeople = append(uniquePeople, p)
		}
	}
	
	// Calculate grid layout with larger boxes
	boxWidth := 220
	boxHeight := 75
	margin := 20
	startX := 30
	startY := 90
	
	cols := (width - 2*startX) / (boxWidth + margin)
	if cols < 1 {
		cols = 1
	}
	
	// Draw each person box
	maxBoxes := 50 // Limit to 50 people for better readability
	for i, person := range uniquePeople {
		if i >= maxBoxes {
			// Add "..." indicator
			moreText := fmt.Sprintf("... and %d more people", len(uniquePeople)-maxBoxes)
			row := i / cols
			col := i % cols
			x := startX + col*(boxWidth+margin)
			y := startY + row*(boxHeight+margin)
			if y < height-60 {
				drawText(img, x+10, y+35, moreText, color.RGBA{100, 100, 100, 255})
			}
			break
		}
		
		row := i / cols
		col := i % cols
		
		x := startX + col*(boxWidth+margin)
		y := startY + row*(boxHeight+margin)
		
		if y+boxHeight > height-60 {
			break // Don't draw boxes that overflow
		}
		
		drawPersonBox(img, x, y, boxWidth, boxHeight, person)
	}
}

// drawPersonBox draws a single person box with text
func drawPersonBox(img *image.RGBA, x, y, width, height int, person *store.Person) {
	// Determine box color by gender
	var boxColor, borderColor color.RGBA
	if person.Gender == "M" {
		boxColor = color.RGBA{173, 216, 230, 255}      // Light blue
		borderColor = color.RGBA{70, 130, 180, 255}    // Steel blue
	} else if person.Gender == "F" {
		boxColor = color.RGBA{255, 192, 203, 255}      // Pink
		borderColor = color.RGBA{219, 112, 147, 255}   // Pale violet red
	} else {
		boxColor = color.RGBA{240, 240, 240, 255}      // Light gray
		borderColor = color.RGBA{150, 150, 150, 255}   // Gray
	}
	
	// Draw filled box
	for py := y; py < y+height; py++ {
		for px := x; px < x+width; px++ {
			if py < y+3 || py >= y+height-3 || px < x+3 || px >= x+width-3 {
				img.Set(px, py, borderColor) // Border
			} else {
				img.Set(px, py, boxColor) // Fill
			}
		}
	}
	
	// Draw person name
	name := formatPersonName(*person)
	// Adjust truncation based on box width (roughly 7 pixels per char in basicfont)
	maxNameChars := (width - 16) / 7
	if len(name) > maxNameChars {
		if maxNameChars > 3 {
			name = name[:maxNameChars-3] + "..."
		} else {
			name = name[:maxNameChars]
		}
	}
	drawText(img, x+8, y+15, name, color.RGBA{0, 0, 0, 255})
	
	// Draw dates
	dates := formatPersonDates(*person)
	if dates != "" {
		maxDateChars := (width - 16) / 7
		if len(dates) > maxDateChars {
			if maxDateChars > 3 {
				dates = dates[:maxDateChars-3] + "..."
			} else {
				dates = dates[:maxDateChars]
			}
		}
		drawText(img, x+8, y+35, dates, color.RGBA{80, 80, 80, 255})
	}
	
	// Draw birth location if available and space permits
	if person.BirthPlace != "" && height > 60 {
		place := person.BirthPlace
		maxPlaceChars := (width - 16) / 7
		if len(place) > maxPlaceChars {
			if maxPlaceChars > 3 {
				place = place[:maxPlaceChars-3] + "..."
			} else {
				place = place[:maxPlaceChars]
			}
		}
		drawText(img, x+8, y+50, place, color.RGBA{100, 100, 100, 255})
	}
}

// drawText draws text on an image using basicfont
func drawText(img *image.RGBA, x, y int, text string, col color.Color) {
	point := fixed.Point26_6{
		X: fixed.Int26_6(x * 64),
		Y: fixed.Int26_6(y * 64),
	}
	
	d := &font.Drawer{
		Dst:  img,
		Src:  image.NewUniform(col),
		Face: basicfont.Face7x13,
		Dot:  point,
	}
	d.DrawString(text)
}

// drawChartFooter draws information footer at bottom
func drawChartFooter(img *image.RGBA, width, height, peopleCount int) {
	// Draw footer background
	footerBg := color.RGBA{240, 240, 240, 255}
	footerY := height - 50
	for y := footerY; y < height; y++ {
		for x := 0; x < width; x++ {
			img.Set(x, y, footerBg)
		}
	}
	
	// Draw top border
	borderColor := color.RGBA{180, 180, 180, 255}
	for x := 0; x < width; x++ {
		for y := footerY; y < footerY+2; y++ {
			img.Set(x, y, borderColor)
		}
	}
	
	// Draw color legend boxes with labels
	legendY := footerY + 15
	legendX := 30
	textColor := color.RGBA{0, 0, 0, 255}
	
	// Male box
	maleColor := color.RGBA{173, 216, 230, 255}
	maleBorder := color.RGBA{70, 130, 180, 255}
	drawLegendBox(img, legendX, legendY, 25, 25, maleColor, maleBorder)
	drawText(img, legendX+32, legendY+18, "Male", textColor)
	
	// Female box
	femaleColor := color.RGBA{255, 192, 203, 255}
	femaleBorder := color.RGBA{219, 112, 147, 255}
	drawLegendBox(img, legendX+150, legendY, 25, 25, femaleColor, femaleBorder)
	drawText(img, legendX+182, legendY+18, "Female", textColor)
	
	// Unknown box
	unknownColor := color.RGBA{240, 240, 240, 255}
	unknownBorder := color.RGBA{150, 150, 150, 255}
	drawLegendBox(img, legendX+310, legendY, 25, 25, unknownColor, unknownBorder)
	drawText(img, legendX+342, legendY+18, "Unknown", textColor)
	
	// Add person count on the right
	countText := fmt.Sprintf("%d people in chart", peopleCount)
	drawText(img, width-250, legendY+18, countText, textColor)
}

// drawLegendBox draws a small legend box
func drawLegendBox(img *image.RGBA, x, y, width, height int, fillColor, borderColor color.RGBA) {
	for py := y; py < y+height; py++ {
		for px := x; px < x+width; px++ {
			if py == y || py == y+height-1 || px == x || px == x+width-1 {
				img.Set(px, py, borderColor)
			} else {
				img.Set(px, py, fillColor)
			}
		}
	}
}

// renderPedigreeChartPNG renders an ancestor/pedigree chart in PNG matching the app layout
func renderPedigreeChartPNG(img *image.RGBA, width, height int, people []*store.Person) {
	if len(people) == 0 {
		return
	}
	
	// Remove duplicates while preserving nils for Ahnentafel numbering
	seen := make(map[int64]bool)
	uniquePeople := make([]*store.Person, len(people))
	for i, p := range people {
		if p != nil {
			if !seen[p.ID] {
				seen[p.ID] = true
				uniquePeople[i] = p
			}
			// If duplicate, leave as nil
		}
		// Preserve nil entries
	}
	
	root := uniquePeople[0]
	
	// Layout constants - compact to fit all 4 generations in 1200px width
	boxWidth := 150
	boxHeight := 70
	colSpacing := 180  // Reduced from 200
	vertSpacing := 85
	startX := 35
	startY := 400  // Increased to center chart and fit all 4 generations
	
	// Draw generation labels
	labelColor := color.RGBA{100, 100, 100, 255}
	drawText(img, startX, 100, "1st", labelColor)
	drawText(img, startX+colSpacing, 100, "2nd", labelColor)
	drawText(img, startX+2*colSpacing, 100, "3rd", labelColor)
	drawText(img, startX+3*colSpacing, 100, "4th", labelColor)
	
	lineColor := color.RGBA{180, 180, 180, 255}
	
	// Generation 1: Root person (use wider box to avoid name truncation)
	y := startY
	rootBoxWidth := 240 // Wider for root person
	drawPersonBox(img, startX, y, rootBoxWidth, boxHeight, root)
	
	// Generation 2: Parents (indices 1-2)
	if len(uniquePeople) > 2 {
		x2 := startX + colSpacing
		
		// Father (top) - index 1
		if uniquePeople[1] != nil {
			yFather := y - vertSpacing
			drawText(img, x2-45, yFather+12, "Father:", color.RGBA{80, 80, 80, 255})
			drawPersonBox(img, x2, yFather, boxWidth, boxHeight, uniquePeople[1])
			// No line from root to parents - relationship is obvious from labels
			drawLine(img, x2+boxWidth, yFather+boxHeight/2, x2+colSpacing-10, yFather+boxHeight/2, lineColor)
		}
		
		// Mother (bottom) - index 2
		if uniquePeople[2] != nil {
			yMother := y + vertSpacing
			drawText(img, x2-45, yMother+12, "Mother:", color.RGBA{80, 80, 80, 255})
			drawPersonBox(img, x2, yMother, boxWidth, boxHeight, uniquePeople[2])
			// No line from root to parents - relationship is obvious from labels
			drawLine(img, x2+boxWidth, yMother+boxHeight/2, x2+colSpacing-10, yMother+boxHeight/2, lineColor)
		}
	}
	
	// Generation 3: Grandparents (indices 3-6)
	// Ahnentafel: 3=paternal grandfather, 4=paternal grandmother, 5=maternal grandfather, 6=maternal grandmother
	if len(uniquePeople) > 6 {
		x3 := startX + 2*colSpacing
		yFather := y - vertSpacing  // Father's Y position
		yMother := y + vertSpacing  // Mother's Y position
		
		// Paternal grandparents (father's parents) - indices 3 and 4
		// Paternal grandfather (index 3) - top of father's line
		if uniquePeople[3] != nil {
			yPG := yFather - vertSpacing/2
			drawPersonBox(img, x3, yPG, boxWidth, boxHeight, uniquePeople[3])
			drawLine(img, x3+boxWidth, yPG+boxHeight/2, x3+colSpacing-10, yPG+boxHeight/2, lineColor)
		}
		
		// Paternal grandmother (index 4) - bottom of father's line
		if uniquePeople[4] != nil {
			yPGM := yFather + vertSpacing/2
			drawPersonBox(img, x3, yPGM, boxWidth, boxHeight, uniquePeople[4])
			drawLine(img, x3+boxWidth, yPGM+boxHeight/2, x3+colSpacing-10, yPGM+boxHeight/2, lineColor)
		}
		
		// Maternal grandparents (mother's parents) - indices 5 and 6
		// Maternal grandfather (index 5) - top of mother's line
		if uniquePeople[5] != nil {
			yMG := yMother - vertSpacing/2
			drawPersonBox(img, x3, yMG, boxWidth, boxHeight, uniquePeople[5])
			drawLine(img, x3+boxWidth, yMG+boxHeight/2, x3+colSpacing-10, yMG+boxHeight/2, lineColor)
		}
		
		// Maternal grandmother (index 6) - bottom of mother's line
		if uniquePeople[6] != nil {
			yMGM := yMother + vertSpacing/2
			drawPersonBox(img, x3, yMGM, boxWidth, boxHeight, uniquePeople[6])
			drawLine(img, x3+boxWidth, yMGM+boxHeight/2, x3+colSpacing-10, yMGM+boxHeight/2, lineColor)
		}
	}
	
	// Generation 4: Great-grandparents (indices 7-14)
	// 7-8: parents of person 3, 9-10: parents of person 4, 11-12: parents of person 5, 13-14: parents of person 6
	if len(uniquePeople) > 7 {
		x4 := startX + 3*colSpacing
		yFather := y - vertSpacing  // Father's Y position (gen 2)
		yMother := y + vertSpacing  // Mother's Y position (gen 2)
		smallSpacing := vertSpacing / 4
		
		// Calculate grandparent Y positions (gen 3)
		yPG := yFather - vertSpacing/2   // Paternal grandfather (person 3)
		yPGM := yFather + vertSpacing/2  // Paternal grandmother (person 4)
		yMG := yMother - vertSpacing/2   // Maternal grandfather (person 5)
		yMGM := yMother + vertSpacing/2  // Maternal grandmother (person 6)
		
		// Parents of paternal grandfather (person 3) - indices 7, 8
		// These should align with person 3's Y position (yPG)
		if len(uniquePeople) > 7 && uniquePeople[7] != nil {
			yGGF1 := yPG - smallSpacing
			if yGGF1 > 115 && yGGF1+boxHeight < height-80 {
				drawPersonBox(img, x4, yGGF1, boxWidth, boxHeight, uniquePeople[7])
			}
		}
		if len(uniquePeople) > 8 && uniquePeople[8] != nil {
			yGGM1 := yPG + smallSpacing
			if yGGM1 > 115 && yGGM1+boxHeight < height-80 {
				drawPersonBox(img, x4, yGGM1, boxWidth, boxHeight, uniquePeople[8])
			}
		}
		
		// Parents of paternal grandmother (person 4) - indices 9, 10
		// These should align with person 4's Y position (yPGM)
		if len(uniquePeople) > 9 && uniquePeople[9] != nil {
			yGGF2 := yPGM - smallSpacing
			if yGGF2 > 115 && yGGF2+boxHeight < height-80 {
				drawPersonBox(img, x4, yGGF2, boxWidth, boxHeight, uniquePeople[9])
			}
		}
		if len(uniquePeople) > 10 && uniquePeople[10] != nil {
			yGGM2 := yPGM + smallSpacing
			if yGGM2 > 115 && yGGM2+boxHeight < height-80 {
				drawPersonBox(img, x4, yGGM2, boxWidth, boxHeight, uniquePeople[10])
			}
		}
		
		// Parents of maternal grandfather (person 5) - indices 11, 12
		// These should align with person 5's Y position (yMG)
		if len(uniquePeople) > 11 && uniquePeople[11] != nil {
			yGGF3 := yMG - smallSpacing
			if yGGF3 > 115 && yGGF3+boxHeight < height-80 {
				drawPersonBox(img, x4, yGGF3, boxWidth, boxHeight, uniquePeople[11])
			}
		}
		if len(uniquePeople) > 12 && uniquePeople[12] != nil {
			yGGM3 := yMG + smallSpacing
			if yGGM3 > 115 && yGGM3+boxHeight < height-80 {
				drawPersonBox(img, x4, yGGM3, boxWidth, boxHeight, uniquePeople[12])
			}
		}
		
		// Parents of maternal grandmother (person 6) - indices 13, 14
		// These should align with person 6's Y position (yMGM)
		if len(uniquePeople) > 13 && uniquePeople[13] != nil {
			yGGF4 := yMGM - smallSpacing
			if yGGF4 > 115 && yGGF4+boxHeight < height-80 {
				drawPersonBox(img, x4, yGGF4, boxWidth, boxHeight, uniquePeople[13])
			}
		}
		if len(uniquePeople) > 14 && uniquePeople[14] != nil {
			yGGM4 := yMGM + smallSpacing
			if yGGM4 > 115 && yGGM4+boxHeight < height-80 {
				drawPersonBox(img, x4, yGGM4, boxWidth, boxHeight, uniquePeople[14])
			}
		}
	}
	
	// Add note if more people exist beyond 4 generations (15 people total: 1+2+4+8)
	if len(uniquePeople) > 15 {
		noteText := fmt.Sprintf("Chart shows 4 generations. View in app for more.")
		drawText(img, 50, height-100, noteText, color.RGBA{100, 100, 100, 255})
	}
}

// renderDescendantChartPNG renders a descendant chart structure in PNG
func renderDescendantChartPNG(img *image.RGBA, width, height int, people []*store.Person, s *store.Store) {
	if len(people) == 0 {
		return
	}
	
	root := people[0]
	
	// Layout constants
	boxWidth := 160
	boxHeight := 65
	vertSpacing := 90
	horizSpacing := 12
	
	startX := 50 // Start from left with padding to fit wider trees
	startY := 120
	
	// Build tree structure using store
	tree := buildDescendantTreeWithStore(root, s, 4) // 4 generations max
	
	// Set box sizes (root gets wider box)
	rootBoxWidth := 240.0 // Wider for root to avoid truncation
	setBoxSizesPNG(tree, rootBoxWidth, float64(boxWidth), float64(boxHeight), true)
	
	// Calculate positions for all nodes
	calculateDescendantPositionsPNG(tree, float64(startX), float64(startY), float64(vertSpacing), float64(horizSpacing))
	
	// Draw the tree
	drawDescendantTreePNG(img, tree)
}

// setBoxSizesPNG recursively sets box sizes for PNG rendering
func setBoxSizesPNG(node *descendantNode, rootWidth, childWidth, height float64, isRoot bool) {
	if node == nil {
		return
	}
	
	if isRoot {
		node.boxWidth = rootWidth
	} else {
		node.boxWidth = childWidth
	}
	node.boxHeight = height
	
	for _, child := range node.children {
		setBoxSizesPNG(child, rootWidth, childWidth, height, false)
	}
}

// calculateDescendantPositionsPNG calculates positions for PNG rendering
func calculateDescendantPositionsPNG(node *descendantNode, x, y, vertSpacing, horizSpacing float64) float64 {
	if node == nil {
		return x
	}
	
	node.x = x
	node.y = y
	
	if len(node.children) == 0 {
		return x + node.boxWidth + horizSpacing
	}
	
	// Position children below
	childY := y + node.boxHeight + vertSpacing
	childX := x
	
	for _, child := range node.children {
		childX = calculateDescendantPositionsPNG(child, childX, childY, vertSpacing, horizSpacing)
	}
	
	// Center parent above children
	if len(node.children) > 0 {
		firstChildX := node.children[0].x
		lastChildX := node.children[len(node.children)-1].x
		node.x = (firstChildX + lastChildX) / 2
	}
	
	return childX
}

// drawDescendantTreePNG draws the descendant tree in PNG
func drawDescendantTreePNG(img *image.RGBA, node *descendantNode) {
	if node == nil {
		return
	}
	
	// Draw this node using its own box size
	drawPersonBox(img, int(node.x), int(node.y), int(node.boxWidth), int(node.boxHeight), node.person)
	
	// Draw lines to children and recurse
	for _, child := range node.children {
		// Draw line from parent to child
		lineColor := color.RGBA{150, 150, 150, 255}
		parentCenterX := int(node.x + node.boxWidth/2)
		parentBottomY := int(node.y + node.boxHeight)
		childCenterX := int(child.x + child.boxWidth/2)
		childTopY := int(child.y)
		
		// Vertical line from parent
		midY := (parentBottomY + childTopY) / 2
		drawLine(img, parentCenterX, parentBottomY, parentCenterX, midY, lineColor)
		// Horizontal line to child
		if parentCenterX < childCenterX {
			drawLine(img, parentCenterX, midY, childCenterX, midY, lineColor)
		} else {
			drawLine(img, childCenterX, midY, parentCenterX, midY, lineColor)
		}
		// Vertical line to child
		drawLine(img, childCenterX, midY, childCenterX, childTopY, lineColor)
		
		drawDescendantTreePNG(img, child)
	}
}


// drawLine draws a line on an image
func drawLine(img *image.RGBA, x1, y1, x2, y2 int, col color.RGBA) {
	// Simple line drawing using Bresenham's algorithm
	dx := x2 - x1
	if dx < 0 {
		dx = -dx
	}
	dy := y2 - y1
	if dy < 0 {
		dy = -dy
	}
	
	var sx, sy int
	if x1 < x2 {
		sx = 1
	} else {
		sx = -1
	}
	if y1 < y2 {
		sy = 1
	} else {
		sy = -1
	}
	
	err := dx - dy
	
	for {
		img.Set(x1, y1, col)
		
		if x1 == x2 && y1 == y2 {
			break
		}
		
		e2 := 2 * err
		if e2 > -dy {
			err -= dy
			x1 += sx
		}
		if e2 < dx {
			err += dx
			y1 += sy
		}
	}
}

// sanitizeFilename removes characters that aren't safe for filenames
func sanitizeFilename(name string) string {
	// Replace common problematic characters
	name = strings.ReplaceAll(name, "/", "-")
	name = strings.ReplaceAll(name, "\\", "-")
	name = strings.ReplaceAll(name, ":", "-")
	name = strings.ReplaceAll(name, "*", "-")
	name = strings.ReplaceAll(name, "?", "-")
	name = strings.ReplaceAll(name, "\"", "-")
	name = strings.ReplaceAll(name, "<", "-")
	name = strings.ReplaceAll(name, ">", "-")
	name = strings.ReplaceAll(name, "|", "-")
	
	// Replace spaces with underscores
	name = strings.ReplaceAll(name, " ", "_")
	
	// Limit length
	if len(name) > 50 {
		name = name[:50]
	}
	
	return name
}
